
logLevel = "debug"

Tasks = [
    {Name = "example_baidu_home", WaitTime = 1, Reload = true, MaxDepth = 1, Fetcher = "browser", Limits=[{EventCount=1, EventDur=1, Bucket=1}]},
    {Name = "xxx"},
]

[fetcher]
timeout = 3000
proxy = []


[storage]
sqlURL = "root:123456@tcp(127.0.0.1:3306)/crawler?charset=utf8"

[GRPCServer]
HTTPListenAddress = ":8080"
GRPCListenAddress = ":9090"
ID = "1"
RegistryAddress = "127.0.0.1:2379"
RegisterTTL = 60
RegisterInterval = 15
ClientTimeOut   = 10
Name = "go.micro.server.worker"

[MasterServer]
RegistryAddress = "127.0.0.1:2379"
RegisterTTL = 60
RegisterInterval = 15
ClientTimeOut   = 10
Name = "go.micro.server.master"
